# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-07-10 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import pm.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('description', models.TextField(blank=True)),
                ('engineer', models.CharField(blank=True, max_length=64, null=True)),
                ('owner', models.CharField(blank=True, max_length=64, null=True)),
                ('location', models.CharField(blank=True, max_length=64, null=True)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ProjectPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(blank=True, upload_to=pm.models.get_file_path)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo', to='pm.Project')),
            ],
            options={
                'verbose_name': 'Project Photo',
                'verbose_name_plural': 'Project Photos',
            },
        ),
        migrations.CreateModel(
            name='Slideshow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_photo', to='pm.ProjectPhoto')),
            ],
            options={
                'verbose_name': 'Slideshow photo',
                'verbose_name_plural': 'Slideshow photos',
            },
        ),
    ]
