# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-07-11 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0002_auto_20180710_2306'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('projects', models.ManyToManyField(to='pm.Project')),
            ],
            options={
                'verbose_name': 'Project Cateogry',
                'verbose_name_plural': 'Project Categories',
            },
        ),
        migrations.AddField(
            model_name='projectphoto',
            name='title',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.RemoveField(
            model_name='slideshow',
            name='project_photo',
        ),
        migrations.AddField(
            model_name='slideshow',
            name='project_photo',
            field=models.ManyToManyField(related_name='project_photo', to='pm.ProjectPhoto'),
        ),
    ]
