# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-07-11 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0003_auto_20180711_1659'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcategory',
            name='projects',
        ),
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.ManyToManyField(related_name='projects', to='pm.ProjectCategory'),
        ),
    ]
