# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-07-11 19:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0006_remove_projectcategory_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcategory',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Position'),
        ),
    ]
