# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-07-11 19:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pm', '0007_projectcategory_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('current', 'Current'), ('past', 'Past'), ('archived', 'Archived')], default='current', max_length=10),
        ),
    ]
