# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-27 15:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_skills', models.TextField(blank=True)),
                ('resume', models.FileField(upload_to='resumes')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(max_length=64)),
                ('last_name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=255)),
                ('address2', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(max_length=255)),
                ('state', localflavor.us.models.USPostalCodeField()),
                ('zipcode', models.CharField(max_length=10)),
                ('phone', localflavor.us.models.PhoneNumberField()),
                ('email', models.EmailField(max_length=254)),
                ('work_eligibility_proof', models.BooleanField(default=True)),
                ('certified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', localflavor.us.models.USPostalCodeField()),
                ('zipcode', models.CharField(max_length=10)),
                ('years_completed', models.CharField(max_length=64)),
                ('degree_earned', models.CharField(max_length=255)),
                ('course_description', models.TextField(blank=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_to_work', models.BooleanField(default=True)),
                ('available_to_work', models.CharField(choices=[('fulltime', 'Full-time'), ('parttime', 'Part-time')], default='fulltime', max_length=20)),
                ('start_work_date', models.DateField(verbose_name='Available for work on')),
                ('currently_employed', models.BooleanField(default=True)),
                ('contact_employer_ok', models.BooleanField(default=True)),
                ('layoff', models.BooleanField(default=True)),
                ('filed_previously', models.BooleanField(default=True)),
                ('filed_previously_date', models.DateField(verbose_name='Previously filed on work on')),
                ('employed_previously', models.BooleanField(default=True)),
                ('employed_previously_date', models.DateField(verbose_name='Previously employed on')),
                ('convicted_felon', models.BooleanField(default=True)),
                ('convicted_information', models.TextField(blank=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_name', models.CharField(max_length=255)),
                ('reference_location', models.CharField(max_length=255)),
                ('reference_phone', localflavor.us.models.PhoneNumberField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', localflavor.us.models.USPostalCodeField()),
                ('zipcode', models.CharField(max_length=10)),
                ('supervisor', models.CharField(max_length=255)),
                ('phone', localflavor.us.models.PhoneNumberField()),
                ('email', models.EmailField(max_length=254)),
                ('start_date', models.DateField(verbose_name='Started work on')),
                ('start_pay', models.DecimalField(decimal_places=2, max_digits=6)),
                ('end_date', models.DateField(verbose_name='Ended work on')),
                ('end_pay', models.DecimalField(decimal_places=2, max_digits=6)),
                ('job_title', models.CharField(max_length=255)),
                ('work_information', models.TextField(blank=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Contact')),
            ],
        ),
        migrations.AddField(
            model_name='additionalinformation',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.Contact'),
        ),
    ]
