# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-17 18:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalinformation',
            options={'verbose_name': 'Additional Information', 'verbose_name_plural': 'Additional Information'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact', 'verbose_name_plural': 'Contacts'},
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Education', 'verbose_name_plural': 'Education'},
        ),
        migrations.AlterModelOptions(
            name='employmentstatus',
            options={'verbose_name': 'Employment Status', 'verbose_name_plural': 'Employment Status'},
        ),
        migrations.AlterModelOptions(
            name='reference',
            options={'verbose_name': 'Reference', 'verbose_name_plural': 'Reference'},
        ),
        migrations.AlterModelOptions(
            name='workexperience',
            options={'verbose_name': 'Work Experience', 'verbose_name_plural': 'Work Experience'},
        ),
        migrations.AddField(
            model_name='contact',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 10, 17, 18, 21, 15, 793251, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 10, 17, 18, 21, 21, 873228, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='work_eligibility_proof',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='contact_employer_ok',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='convicted_felon',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='currently_employed',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='employed_previously',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='filed_previously',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='layoff',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='legal_to_work',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
