# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-24 13:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_auto_20161017_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='workexperience',
            name='end_pay_cycle',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('annually', 'Annually')], default='hourly', max_length=8),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='start_pay_cycle',
            field=models.CharField(choices=[('hourly', 'Hourly'), ('weekly', 'Weekly'), ('biweekly', 'Bi-Weekly'), ('monthly', 'Monthly'), ('annually', 'Annually')], default='hourly', max_length=8),
        ),
        migrations.AlterField(
            model_name='additionalinformation',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additionalinformation', to='jobs.Contact'),
        ),
        migrations.AlterField(
            model_name='education',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='jobs.Contact'),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employmentstatus', to='jobs.Contact'),
        ),
        migrations.AlterField(
            model_name='reference',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference', to='jobs.Contact'),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workexperience', to='jobs.Contact'),
        ),
    ]
