# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-24 19:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20161024_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workexperience',
            name='end_pay',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='start_pay',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
