# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-10-25 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_contact_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employmentstatus',
            name='available_to_work',
            field=models.CharField(choices=[('fulltime', 'Full-time'), ('parttime', 'Part-time')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='contact_employer_ok',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='convicted_felon',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='currently_employed',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='employed_previously',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='filed_previously',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='layoff',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='legal_to_work',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=None),
        ),
    ]
