# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20161025_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinformation',
            name='resume',
            field=models.FileField(blank=True, upload_to='resumes'),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='employed_previously_date',
            field=models.DateField(blank=True, default=None, verbose_name='Previously employed on'),
        ),
        migrations.AlterField(
            model_name='employmentstatus',
            name='filed_previously_date',
            field=models.DateField(blank=True, default=None, verbose_name='Previously filed on work on'),
        ),
    ]
