# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 02:47
from __future__ import unicode_literals

from django.db import migrations, models
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_auto_20161115_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalinformation',
            name='resume',
            field=models.FileField(blank=True, upload_to=jobs.models.get_file_path),
        ),
    ]
