# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-04-15 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20161115_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', localflavor.us.models.USPostalCodeField()),
            ],
        ),
        migrations.AlterField(
            model_name='contact',
            name='middle_name',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='employmentstatus',
            name='states_available_work',
            field=models.ManyToManyField(to='jobs.WorkState', verbose_name='States available for work'),
        ),
    ]
